apiVersion: v1
kind: Service
metadata:
  name: nsqadmin
  labels:
    app: nsqadmin
spec:
  ports:
  - port: 4170
    name: tcp
  - port: 4171
    name: http
  selector:
    name: nsqadmin
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nsqadmin
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: nsqadmin
  template:
    metadata:
      labels:
        name: nsqadmin
    spec:
      containers:
      - name: nsqadmin
        image: mhlg/rpi-nsq:1.0.2
        resources:
          requests:
            memory: 50M
        imagePullPolicy: Always
        command:
        - nsqadmin
        - "-lookupd-http-address=nsqlookupd-0.nsqlookupd:4161"
        ports:
        - containerPort: 4170
          name: tcp
        - containerPort: 4171
          name: http


