apiVersion: v1
kind: Service
metadata:
  name: nsqlookupd
  labels:
    app: nsqlookupd
spec:
  ports:
  - port: 4160
    name: tcp
  - port: 4161
    name: http
  clusterIP: None
  selector:
    app: nsqlookupd
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nsqlookupd
spec:
  serviceName: nsqlookupd
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nsqlookupd
    spec:
      hostNetwork: true
      containers:
      - name: nsqlookupd
        image: mhlg/rpi-nsq:1.0.2
        resources:
          requests:
            memory: 100M
        imagePullPolicy: Always
        command:
        - nsqlookupd
        ports:
        - containerPort: 4160
          name: tcp
        - containerPort: 4161
          name: http
        livenessProbe:
          httpGet:
            path: /ping
            port: 4161
          initialDelaySeconds: 3
          periodSeconds: 3
